In [1]:
import librosa
import librosa.display
import IPython.display as ipd
import matplotlib.pyplot as plt
import numpy as np
import numpy as np
from sklearn import svm
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
base_path = "/content/drive/MyDrive/KuliahSmst4/PPDM"

In [4]:
def get_zero(number):
  len_num = 4
  len_number = len(str(number))
  return "0" * (len_num - len_number)

In [5]:
total_data_happy = 1061
name_audio_happy = []
label_audio_happy = [1 for i in range(total_data_happy)]
for i in range(total_data_happy):
  temp = get_zero(i+1)
  name_audio_happy.append(f"{base_path}/Happy/happy-{temp}{i+1}.wav")


In [6]:
total_data_happy = 1088
name_audio_sad = []
label_audio_sad = [0 for i in range(total_data_happy)]
for i in range(total_data_happy):
  temp = get_zero(i+1)
  name_audio_sad.append(f"{base_path}/Sad/sad-{temp}{i+1}.wav")

In [7]:
feature_vectors = []
labels = []

In [8]:
for audio_file in name_audio_happy:
  audio, sr = librosa.load(audio_file, sr=None)  # Load the audio file
  mfccs = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=13)  # Extract 13 MFCCs
  mfcc_scaled_features = np.mean(mfccs.T, axis=0)
  feature_vectors.append(mfcc_scaled_features)


for i in label_audio_happy:
  labels.append(i)

In [9]:
len(feature_vectors)
feature_vectors

[array([-2.7590280e+02,  9.7095207e+01,  1.6553730e+00,  1.3734499e+01,
         2.5650103e+00, -9.2972393e+00,  2.5570637e-01, -5.0184588e+00,
        -4.7418656e+00,  1.8664052e+00, -7.6533904e+00, -2.0268073e+00,
        -4.5299430e+00], dtype=float32),
 array([-355.49246  ,  102.29577  ,   31.163507 ,   25.574123 ,
          13.689903 ,   -7.0720825,   -1.1663718,   -0.7100519,
          -3.8168855,   -3.2959926,   -6.272252 ,   -3.9147332,
          -2.4290779], dtype=float32),
 array([-332.38745   ,  107.06651   ,   27.02897   ,   33.062073  ,
           5.2287073 ,   -5.4489923 ,   -2.2885165 ,  -10.12782   ,
           0.34096906,   -3.163466  ,   -4.288528  ,   -1.5419935 ,
          -9.773943  ], dtype=float32),
 array([-3.3309641e+02,  1.0944141e+02,  1.6242960e+01,  2.7857601e+01,
         2.1568546e+00, -5.0534520e+00, -1.5605979e+00, -5.4125509e+00,
         6.7499771e+00, -3.5660014e+00, -2.5954657e+00,  1.1344304e-01,
        -6.3726387e+00], dtype=float32),
 array([-30

In [10]:
mfccs
mfcc_scaled_features

array([-2.9169437e+02,  1.1887358e+02,  1.2449064e+01,  2.0554169e+01,
       -1.3152246e+01, -5.6379633e+00,  9.0978107e+00, -1.7181414e+01,
       -1.5820700e+00,  2.8765512e-01, -6.9102793e+00,  2.4580741e+00,
       -4.0895700e+00], dtype=float32)

In [11]:
for audio_file in name_audio_sad:
  audio, sr = librosa.load(audio_file, sr=None)  # Load the audio file
  mfccs = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=13)  # Extract 13 MFCCs
  mfcc_scaled_features = np.mean(mfccs.T, axis=0)
  feature_vectors.append(mfcc_scaled_features)

for i in label_audio_sad:
  labels.append(i)

In [12]:
# Convert feature_vectors to a numpy array
X = feature_vectors
y = labels

In [13]:
len(X)
X

[array([-2.7590280e+02,  9.7095207e+01,  1.6553730e+00,  1.3734499e+01,
         2.5650103e+00, -9.2972393e+00,  2.5570637e-01, -5.0184588e+00,
        -4.7418656e+00,  1.8664052e+00, -7.6533904e+00, -2.0268073e+00,
        -4.5299430e+00], dtype=float32),
 array([-355.49246  ,  102.29577  ,   31.163507 ,   25.574123 ,
          13.689903 ,   -7.0720825,   -1.1663718,   -0.7100519,
          -3.8168855,   -3.2959926,   -6.272252 ,   -3.9147332,
          -2.4290779], dtype=float32),
 array([-332.38745   ,  107.06651   ,   27.02897   ,   33.062073  ,
           5.2287073 ,   -5.4489923 ,   -2.2885165 ,  -10.12782   ,
           0.34096906,   -3.163466  ,   -4.288528  ,   -1.5419935 ,
          -9.773943  ], dtype=float32),
 array([-3.3309641e+02,  1.0944141e+02,  1.6242960e+01,  2.7857601e+01,
         2.1568546e+00, -5.0534520e+00, -1.5605979e+00, -5.4125509e+00,
         6.7499771e+00, -3.5660014e+00, -2.5954657e+00,  1.1344304e-01,
        -6.3726387e+00], dtype=float32),
 array([-30

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
# 4. SVM Model Training
svm_model = svm.SVC(C=0.1, kernel='poly', gamma=0.00001)
svm_model.fit(X_train, y_train)

SVC(C=0.1, gamma=1e-05, kernel='poly')

In [16]:
# 5. Model Evaluation
y_pred = svm_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

Accuracy: 0.8534883720930233
Precision: 0.8686868686868687
Recall: 0.8229665071770335
F1-Score: 0.8452088452088452


In [21]:
import pandas as pd
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Load dataset
X = feature_vectors
y = labels

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Set the parameters to be tuned
parameters = {'kernel': ['poly', 'rbf'], 'C': [0.1, 1, 10, 100]}

# Create SVM classifier
svm_classifier = svm.SVC()

# Perform grid search with cross-validation
grid_search = GridSearchCV(svm_classifier, parameters)
grid_search.fit(X_train, y_train)

# Get the results as a DataFrame
results_df = pd.DataFrame(grid_search.cv_results_)

# Evaluate the classifier on the testing set
best_classifier = grid_search.best_estimator_
y_pred = best_classifier.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

results_df['accuracy'] = accuracy
results_df['precision'] = precision
results_df['recall'] = recall
results_df['f1_score'] = f1

# Display the results in a table
print(results_df[['params', 'mean_test_score', 'accuracy', 'precision', 'recall', 'f1_score']].to_string(index=False))

# Print the best parameters and the best score
print("\nBest parameters:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)

# Print evaluation metrics
best_classifier = grid_search.best_estimator_
accuracy = best_classifier.score(X_test, y_test)
print("Accuracy:", accuracy)
precision = best_classifier.score(X_test, y_test)
print("Precision:", precision)
recall = best_classifier.score(X_test, y_test)
print("Recall:", recall)
f1 = best_classifier.score(X_test, y_test)
print("F1-Score:", f1)

                      params  mean_test_score  accuracy  precision   recall  f1_score
{'C': 0.1, 'kernel': 'poly'}         0.852810  0.851163   0.851321 0.851163  0.851076
 {'C': 0.1, 'kernel': 'rbf'}         0.846422  0.851163   0.851321 0.851163  0.851076
  {'C': 1, 'kernel': 'poly'}         0.849322  0.851163   0.851321 0.851163  0.851076
   {'C': 1, 'kernel': 'rbf'}         0.854555  0.851163   0.851321 0.851163  0.851076
 {'C': 10, 'kernel': 'poly'}         0.859794  0.851163   0.851321 0.851163  0.851076
  {'C': 10, 'kernel': 'rbf'}         0.856884  0.851163   0.851321 0.851163  0.851076
{'C': 100, 'kernel': 'poly'}         0.866189  0.851163   0.851321 0.851163  0.851076
 {'C': 100, 'kernel': 'rbf'}         0.863865  0.851163   0.851321 0.851163  0.851076

Best parameters: {'C': 100, 'kernel': 'poly'}
Best score: 0.8661892331683504
Accuracy: 0.8511627906976744
Precision: 0.8511627906976744
Recall: 0.8511627906976744
F1-Score: 0.8511627906976744


In [22]:
import pickle
# Save the trained SVM model to a .pkl file
model_path = "svm.pkl"
with open(model_path, 'wb') as file:
    pickle.dump(svm_model, file)

In [23]:
import librosa
import numpy as np
import pickle

# Define the path to your saved SVM model (.pkl file)
model_path = "svm.pkl"

# Function to extract MFCC features from audio files
def extract_features(file_path):
    audio, sample_rate = librosa.load(file_path, sr=None)
    mfcc_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=13)
    mfcc_scaled_features = np.mean(mfcc_features.T, axis=0)
    return mfcc_scaled_features

# Function to predict the emotion of a new audio file
def predict_emotion(file_path, model):
    # Extract features from the new audio file
    features = extract_features(file_path)

    # Reshape the features into a single sample
    features = features.reshape(1, -1)

    # Predict the emotion using the loaded SVM model
    emotion = model.predict(features)[0]

    return emotion

# Path to the new audio file for prediction
new_audio_path = "Girl - Sad Call Recording.mp3"

# Load the trained SVM model from the .pkl file
with open(model_path, 'rb') as file:
    trained_model = pickle.load(file)

label_to_emotion = {0: 'sad', 1: 'happy'}

# Predict the emotion of the new audio file using the loaded model
predicted_emotion = predict_emotion(new_audio_path, trained_model)
print("Predicted Emotion:", label_to_emotion[predicted_emotion])

Predicted Emotion: sad
